name: Build project
on:
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up JDK 1.8
          uses: actions/setup-java@v3
          with:
            java-version: 1.8
            distribution: microsoft

        - name: Setup Android SDK
          uses: android-actions/setup-android@v2

        - name: Build SampleApplication
          run: ./gradlew --no-daemon build
